In [1]:
## transformer

In [21]:
import torch
import torch.nn.functional as F

In [ ]:
def attention(query, key, value, mask=None, dropout=None):
    "计算Attention即点乘V"
    d_k = query.size(-1)
    # [B, h, L, L]
    scores = torch.matmul(query, key.transpose(-2, -1)) \
             / math.sqrt(d_k)
    if mask is not None:
        scores = scores.masked_fill(mask == 0, -1e9)
    p_attn = F.softmax(scores, dim = -1)
    if dropout is not None:
        p_attn = dropout(p_attn)
    return torch.matmul(p_attn, value), p_attn

In [42]:
key = torch.tensor(
[[1,2,3],
[1,1,1]])

In [43]:
key

tensor([[1, 2, 3],
        [1, 1, 1]])

In [44]:
key.transpose(-2, -1)

tensor([[1, 1],
        [2, 1],
        [3, 1]])

In [45]:
scores = torch.matmul(key,key.transpose(-2, -1))
scores

tensor([[14,  6],
        [ 6,  3]])

In [46]:
att = F.softmax(scores.float(), dim = -1)
att

tensor([[9.9966e-01, 3.3535e-04],
        [9.5257e-01, 4.7426e-02]])

In [47]:
key

tensor([[1, 2, 3],
        [1, 1, 1]])

In [48]:
torch.matmul(att, key.float())

tensor([[1.0000, 1.9997, 2.9993],
        [1.0000, 1.9526, 2.9051]])

## 下三角

In [49]:
import numpy as np

In [ ]:
def mask_seq(size):
    mask_shape = (1, size, size)
    

In [50]:
x = np.ones((1, 5, 5))

In [51]:
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [57]:
shang = np.triu(x, k=1).astype('uint8')
shang

array([[[0, 1, 1, 1, 1],
        [0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]]], dtype=uint8)

In [61]:
torch.from_numpy(shang==0) *1.2

tensor([[[1.2000, 0.0000, 0.0000, 0.0000, 0.0000],
         [1.2000, 1.2000, 0.0000, 0.0000, 0.0000],
         [1.2000, 1.2000, 1.2000, 0.0000, 0.0000],
         [1.2000, 1.2000, 1.2000, 1.2000, 0.0000],
         [1.2000, 1.2000, 1.2000, 1.2000, 1.2000]]])