In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F

## nn.Embedding介绍
- [https://pytorch.org/docs/stable/nn.html](https://pytorch.org/docs/stable/nn.html)
----
- pytorch里面实现word embedding是通过一个函数来实现的:nn.Embedding。Embedding的作用就是将词语向量化，通常会将词语表示为一个连续箱梁。
- 官方介绍
    - 一个简单的查找表，用于存储固定字典和大小的嵌入。
    - 此模块通常用于存储单词嵌入并使用索引检索它们。模块的输入是索引列表，输出是相应的字嵌入。
    
- CLASS torch.nn.Embedding(num_embeddings, embedding_dim, padding_idx=None, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, sparse=False, _weight=None)

- 参数：
    - num_embeddings (int) – 词典的大小，也就是词典有多少个词。比如你有一个30000的词典，这里就是30000.

    - embedding_dim (int) – the size of each embedding vector。将词语表示成embedding_dim维的向量。指定向量的维度。

    - padding_idx (int, optional) – If given, pads the output with the embedding vector at padding_idx (initialized to zeros) whenever it encounters the index.设置padding_idx后，padding_idx中的嵌入向量将初始化为全零。但是，请注意，之后可以修改该向量，例如，使用定制的初始化方法，从而改变用于填充输出的向量。嵌入中此向量的渐变始终为零。

    - max_norm (float, optional) – If given, each embedding vector with norm larger than max_norm is renormalized to have norm max_norm.
    - norm_type (float, optional) – The p of the p-norm to compute for the max_norm option. Default 2.
    - scale_grad_by_freq (boolean, optional) – If given, this will scale gradients by the inverse of frequency of the words in the mini-batch. Default False.
    - sparse (bool, optional) – If True, gradient w.r.t. weight matrix will be a sparse tensor. See Notes for more details regarding sparse gradients.
- 看个例子吧

In [2]:
# 定义一个词典：word2idx = {'hello': 0, 'world': 1, '!':2}，每个单词我们需要用一个数字去表示它，这里对于hello这个词，用0来表示它。
word2idx = {'hello': 0, 'world': 1, '!':2}

# 定义Embedding层，这里的3表示词典共有3个词，5表示5维度，其实也就是一个3x5的矩阵.
# 如果你有1000个词，每个词希望是100维，你就可以这样建立一个word embedding，nn.Embedding(1000, 100)。
# 这就相当于词语和表示词语的向量建立了一张表，想知道一个词的向量表示可以通过这张表去查。
embeds = nn.Embedding(3, 5)

# 如何查询hello这个词的向量表示呢？

# 通过词语在原来字典中的索引查词向量，hello的索引是0
hello_idx = torch.LongTensor([word2idx['hello']])

# 特别注意这里需要一个Variable，因为我们需要访问nn.Embedding里面定义的元素，且word embeding算是神经网络里面的参数，所以我们需要定义Variable
hello_idx = Variable(hello_idx)
# 现在输入Variable格式的索引就可以查看词向量了
hello_embed = embeds(hello_idx)

# 输出hello这个词的<初始词向量>
print(hello_embed)

tensor([[ 0.3746, -1.0797, -0.6317, -0.6281, -0.4120]],
       grad_fn=<EmbeddingBackward>)


## 注意
- 注意这里的词向量的建立只是**初始的词向量**，并没有经过任何修改优化，我们需要建立神经网络通过learning修改word embedding里面的参数使得word embedding每一个词向量能够表示每一个不同的词。

## nn.LSTM

In [2]:
rnn = nn.LSTM(10, 20)     

In [3]:
input_data = torch.randn(5, 3, 10)  # seq_len, batch, input_size

In [4]:
# h0 = torch.randn(1, 3, 20)   # 初始化
# h0

In [5]:
# c0 = torch.randn(1, 3, 20)
# c0

In [6]:
output, (hn, cn) = rnn(input_data)

In [7]:
output.size()

torch.Size([5, 3, 20])

In [10]:
output[4]

tensor([[-0.1023, -0.2195, -0.3629, -0.0977, -0.1240, -0.1357, -0.2260, -0.0529,
          0.0173,  0.0663,  0.0418, -0.0313, -0.1414,  0.1390,  0.0395, -0.2833,
          0.0786, -0.0190,  0.0141, -0.0871],
        [-0.0481, -0.1797, -0.0957, -0.0579,  0.0646, -0.1703,  0.0248, -0.1381,
         -0.1028,  0.1341,  0.1645,  0.0634, -0.1689,  0.0230, -0.0375, -0.1674,
         -0.0029, -0.0914,  0.0958, -0.0738],
        [-0.0141, -0.0795,  0.0149,  0.0237,  0.0830, -0.2079,  0.2409, -0.0418,
         -0.0247,  0.2118,  0.1507, -0.0559, -0.1114, -0.0887, -0.2693, -0.0222,
          0.0394, -0.0820, -0.0806, -0.0231]], grad_fn=<SelectBackward>)

In [11]:
hn

tensor([[[-0.1023, -0.2195, -0.3629, -0.0977, -0.1240, -0.1357, -0.2260,
          -0.0529,  0.0173,  0.0663,  0.0418, -0.0313, -0.1414,  0.1390,
           0.0395, -0.2833,  0.0786, -0.0190,  0.0141, -0.0871],
         [-0.0481, -0.1797, -0.0957, -0.0579,  0.0646, -0.1703,  0.0248,
          -0.1381, -0.1028,  0.1341,  0.1645,  0.0634, -0.1689,  0.0230,
          -0.0375, -0.1674, -0.0029, -0.0914,  0.0958, -0.0738],
         [-0.0141, -0.0795,  0.0149,  0.0237,  0.0830, -0.2079,  0.2409,
          -0.0418, -0.0247,  0.2118,  0.1507, -0.0559, -0.1114, -0.0887,
          -0.2693, -0.0222,  0.0394, -0.0820, -0.0806, -0.0231]]],
       grad_fn=<StackBackward>)

## 结论
- 我们可以看到hn是最后一次输出，output是所有输出。因此output的最后一个元素和hn是一样的。
- cn是细胞状态tensor

In [12]:
hn.size()

torch.Size([1, 3, 20])

In [13]:
cn.size()

torch.Size([1, 3, 20])

In [14]:
cn

tensor([[[-0.2094, -0.5293, -0.7267, -0.1446, -0.1959, -0.2274, -0.4356,
          -0.1363,  0.0553,  0.1174,  0.1804, -0.1037, -0.3693,  0.3561,
           0.0795, -0.5906,  0.2023, -0.0374,  0.0280, -0.2041],
         [-0.1044, -0.4315, -0.1768, -0.1072,  0.1064, -0.3795,  0.0522,
          -0.3305, -0.2329,  0.2719,  0.3601,  0.1317, -0.4066,  0.0497,
          -0.0728, -0.4711, -0.0061, -0.1587,  0.1639, -0.1596],
         [-0.0240, -0.2553,  0.0266,  0.0601,  0.1633, -0.5237,  0.4116,
          -0.0992, -0.0575,  0.3210,  0.2774, -0.1068, -0.2709, -0.1610,
          -0.4528, -0.0570,  0.0676, -0.1944, -0.1193, -0.0365]]],
       grad_fn=<StackBackward>)

In [13]:
fc = nn.Linear(20, 20)

In [14]:
out = fc(output)

In [15]:
out.size()

torch.Size([5, 3, 20])

In [16]:
out[0][0]

tensor([ 0.0896, -0.0571, -0.0152, -0.0691, -0.0199, -0.0406,  0.2308, -0.2142,
        -0.1767, -0.0639, -0.0081,  0.1343, -0.1078, -0.2064, -0.1733, -0.1182,
         0.1361, -0.2758,  0.1620,  0.1076], grad_fn=<SelectBackward>)

In [17]:
rnn2 = nn.LSTM(10, 20, batch_first=True) 

In [18]:
# bacth,seq_len, word_vec_dim
input_data2 = torch.randn(32, 5, 10)  # hc层size(layer_num, bacth, out_dim)

In [19]:
out, (hn, cn) = rnn2(input_data2)

In [20]:
print(out.size(), hn.size(), cn.size())

torch.Size([32, 5, 20]) torch.Size([1, 32, 20]) torch.Size([1, 32, 20])


In [21]:
a = torch.randn(2).unsqueeze(0)

In [22]:
a

tensor([[-0.4607, -0.4461]])

## 两个形状相同的tonsor相乘

In [23]:
a = torch.tensor([[1,2,3], 
                  [2,3,4]])
b = torch.tensor([[2,2,2], 
                  [2,2,1]])

In [24]:
c = a*b
c

tensor([[2, 4, 6],
        [4, 6, 4]])

In [25]:
a = torch.randn(2, 5, 10)
a

tensor([[[ 1.0323,  0.1239,  1.1077,  0.2164,  0.4767,  0.4025,  0.2399,
          -0.1330,  0.5671,  0.1008],
         [ 0.0843,  0.7463,  0.6705,  0.1488,  0.6736, -0.2464, -0.5746,
           0.6086,  0.9737,  0.0711],
         [ 1.8035,  0.8987, -0.6655, -1.0680, -0.5026,  0.5141,  1.4208,
           0.2101,  0.4502,  1.3422],
         [ 1.0504,  1.3057,  0.2206, -1.7455, -1.2488, -0.4145,  0.8532,
           0.8481,  0.6439,  0.8128],
         [ 0.7198,  0.6862,  0.3618,  0.1609, -0.0922, -0.3626,  0.5601,
          -0.0230, -1.4171, -0.9066]],

        [[ 1.2316,  0.4093, -0.0454, -0.0887, -0.0333, -0.4516,  0.8812,
           0.6673, -2.0286,  0.5245],
         [-0.6719, -1.0660,  1.0303, -2.0076, -0.1587, -0.7049, -0.4192,
          -1.6840, -0.0913, -0.8211],
         [-0.0361,  1.6295, -0.2098, -0.5681,  0.6524,  0.3682, -1.0326,
           0.8690, -0.8374, -0.7785],
         [-1.1685, -0.4528,  0.8089, -0.6248, -1.4823,  1.7067,  0.0343,
          -0.1233, -0.4694,  0.7405],

In [26]:
c = a.sum(2)
c.size()

torch.Size([2, 5])

In [27]:
x = torch.randn([2,3,5])
x 

tensor([[[-0.1212, -1.1875, -0.8154, -0.2603,  0.1208],
         [-1.7234,  0.9401,  0.5191, -1.1418,  0.0485],
         [-0.5145,  0.5186,  0.4932,  0.5364, -0.8625]],

        [[-0.2743, -0.4564,  1.8824,  0.5533,  2.1877],
         [-0.9605,  1.0729,  0.4791, -0.9585, -0.0132],
         [-1.3529, -0.8772,  0.2921, -0.8205, -0.1080]]])

In [28]:
mask = (x>0)
mask

tensor([[[0, 0, 0, 0, 1],
         [0, 1, 1, 0, 1],
         [0, 1, 1, 1, 0]],

        [[0, 0, 1, 1, 1],
         [0, 1, 1, 0, 0],
         [0, 0, 1, 0, 0]]], dtype=torch.uint8)

In [29]:
d = x[mask]    # 压扁成一个列表
d

tensor([0.1208, 0.9401, 0.5191, 0.0485, 0.5186, 0.4932, 0.5364, 1.8824, 0.5533,
        2.1877, 1.0729, 0.4791, 0.2921])

In [30]:
import torch.nn.functional as F

In [31]:
s = F.logsigmoid(d)

In [32]:
s.mean()   # 得到一个数字

tensor(-0.4262)

In [33]:
torch.log(1 - torch.sigmoid(d)).mean()

tensor(-1.1681)

## nn.Parameter

In [34]:
?nn.Parameter

In [38]:
embed_dim = 10
data = torch.randn(embed_dim)
data.size()

torch.Size([10])

In [39]:
u = nn.Parameter(data)

In [40]:
u

Parameter containing:
tensor([-0.6100,  0.1809,  0.7675, -0.5735,  0.1123,  0.4894, -0.8654, -1.0640,
        -1.2618, -0.8684], requires_grad=True)

In [41]:
embed = torch.randn(4, 8, 10)  #[batch, seq_len, embed]
embed

tensor([[[ 0.5720, -0.4873, -0.1925, -0.1972, -0.0626,  1.5768,  1.0680,
           1.2321, -0.4564, -0.0703],
         [ 0.5284, -0.7402,  0.4011,  0.0832, -1.9947, -0.9723,  0.9434,
           0.4962,  0.3930,  0.5200],
         [ 0.2165,  0.9300,  1.4055, -0.9435, -0.1495, -0.5030,  0.3633,
           0.9413,  1.4385, -0.7606],
         [ 0.2950,  0.9037, -0.9711,  0.0556, -1.5093, -1.8391, -0.6188,
          -1.2471, -0.8059, -0.6884],
         [ 1.0337, -0.6484,  2.1221,  0.9859,  2.1802, -2.2094, -0.0289,
           0.8381,  0.3553,  0.2861],
         [-0.1302,  1.4063,  0.4567, -1.1085,  1.9764, -0.1228,  0.9814,
           0.9537, -0.6450,  0.7175],
         [-0.1446, -0.1117,  0.0594, -1.7827, -0.4155, -0.0715,  0.0213,
           0.7226,  0.6909,  1.2786],
         [ 0.6332,  0.4564, -0.1636,  0.3665,  0.6061, -0.0314, -1.5227,
           0.0369,  1.3917, -0.5979]],

        [[-1.3836, -0.8652, -1.3644, -0.8995, -0.2949,  1.2752,  0.1303,
          -0.1627, -0.0075,  0.5403],

In [46]:
x = u.repeat(embed.size(0), embed.size(1), 1)
x.size()

torch.Size([4, 8, 10])

In [70]:
cos = F.cosine_similarity(embed, x, dim=2)
cos

tensor([[-0.2212, -0.4839, -0.1610,  0.2061, -0.2068, -0.0250, -0.2900, -0.0944],
        [ 0.0531, -0.2761, -0.0455,  0.3600, -0.0608, -0.4872, -0.3845,  0.6251],
        [ 0.0520,  0.1996, -0.5176, -0.5650,  0.6570, -0.0836,  0.0536, -0.3301],
        [-0.3879,  0.2709,  0.0507,  0.6181,  0.4528, -0.0298,  0.2379, -0.4050]],
       grad_fn=<DivBackward0>)

In [77]:
alpha = F.softmax(cos, dim=1)  # 每个序列一行，每每行的每个元素代表对应的单词的权重
alpha

tensor([[0.1154, 0.0888, 0.1226, 0.1769, 0.1171, 0.1404, 0.1077, 0.1310],
        [0.1270, 0.0913, 0.1150, 0.1725, 0.1133, 0.0740, 0.0820, 0.2249],
        [0.1307, 0.1515, 0.0739, 0.0705, 0.2393, 0.1141, 0.1309, 0.0892],
        [0.0724, 0.1398, 0.1122, 0.1979, 0.1677, 0.1035, 0.1353, 0.0711]],
       grad_fn=<SoftmaxBackward>)

In [113]:
d = alpha.unsqueeze(2)
print(embed[0][0][0]*d[0][0][0],embed[0][0][1]*d[0][0][0])

tensor(0.0660, grad_fn=<MulBackward0>) tensor(-0.0562, grad_fn=<MulBackward0>)


In [110]:
embed*alpha.unsqueeze(2)

tensor([[[ 0.0660, -0.0562, -0.0222, -0.0228, -0.0072,  0.1820,  0.1233,
           0.1422, -0.0527, -0.0081],
         [ 0.0469, -0.0657,  0.0356,  0.0074, -0.1770, -0.0863,  0.0837,
           0.0440,  0.0349,  0.0462],
         [ 0.0265,  0.1140,  0.1723, -0.1157, -0.0183, -0.0617,  0.0445,
           0.1154,  0.1763, -0.0932],
         [ 0.0522,  0.1599, -0.1718,  0.0098, -0.2671, -0.3254, -0.1095,
          -0.2207, -0.1426, -0.1218],
         [ 0.1210, -0.0759,  0.2485,  0.1154,  0.2553, -0.2587, -0.0034,
           0.0981,  0.0416,  0.0335],
         [-0.0183,  0.1975,  0.0641, -0.1557,  0.2776, -0.0173,  0.1378,
           0.1339, -0.0906,  0.1008],
         [-0.0156, -0.0120,  0.0064, -0.1921, -0.0448, -0.0077,  0.0023,
           0.0779,  0.0744,  0.1378],
         [ 0.0830,  0.0598, -0.0214,  0.0480,  0.0794, -0.0041, -0.1995,
           0.0048,  0.1823, -0.0783]],

        [[-0.1756, -0.1098, -0.1732, -0.1142, -0.0374,  0.1619,  0.0165,
          -0.0207, -0.0010,  0.0686],

In [90]:
y = torch.sum(embed*alpha.unsqueeze(2), dim=1)
y

tensor([[ 0.3618,  0.3213,  0.3114, -0.3055,  0.0978, -0.5791,  0.0793,  0.3957,
          0.2237,  0.0167],
        [-0.1417, -0.2927, -0.7323, -0.2796, -0.4680, -0.2061, -0.6581, -0.1812,
         -0.8672,  0.0082],
        [-0.1451,  0.0247,  0.1265, -0.2745,  0.0626, -0.3589, -0.2194, -0.0770,
          0.2479, -0.5162],
        [-0.4050, -0.7885,  0.4427, -0.3342, -0.5260,  0.2249,  0.0418, -0.6697,
         -0.5975,  0.1450]], grad_fn=<SumBackward2>)

In [91]:
y.size()

torch.Size([4, 10])

In [92]:
y.squeeze(1)

tensor([[ 0.3618,  0.3213,  0.3114, -0.3055,  0.0978, -0.5791,  0.0793,  0.3957,
          0.2237,  0.0167],
        [-0.1417, -0.2927, -0.7323, -0.2796, -0.4680, -0.2061, -0.6581, -0.1812,
         -0.8672,  0.0082],
        [-0.1451,  0.0247,  0.1265, -0.2745,  0.0626, -0.3589, -0.2194, -0.0770,
          0.2479, -0.5162],
        [-0.4050, -0.7885,  0.4427, -0.3342, -0.5260,  0.2249,  0.0418, -0.6697,
         -0.5975,  0.1450]], grad_fn=<SqueezeBackward1>)

In [97]:
fx = nn.Linear(10,1)(y)
fx

tensor([[0.4853],
        [0.5154],
        [0.4474],
        [0.1978]], grad_fn=<AddmmBackward>)

In [101]:
score = torch.sigmoid(fx) # 0-1之间的数
score

tensor([[0.6190],
        [0.6261],
        [0.6100],
        [0.5493]], grad_fn=<SigmoidBackward>)

In [106]:
torch.round(score) #返回相邻最近的整数，四舍五入

tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<RoundBackward>)

## torch.nn.functional.cosine_similarity计算方法

In [48]:
x1 = torch.randn(2,3)
x2 = torch.randn(2,3)
print(x1, x2)

tensor([[ 0.3437,  0.3895,  1.4366],
        [-3.1125, -0.4749, -0.6235]]) tensor([[-0.9672,  0.4503, -0.3470],
        [ 0.2393,  1.8958, -1.3947]])


In [49]:
F.cosine_similarity(x1, x2)

tensor([-0.3825, -0.1021])

In [64]:
# cosine_similarity的计算公式
sum(x1[0]*x2[0]) / (torch.norm(x1[0])*torch.norm(x2[0])+1e-8)

tensor(-0.3825)

## 截断函数
----
- torch.ceil(input, out=None)   #返回向正方向取得最小整数
- torch.floor(input, out=None)  #返回向负方向取得最大整数

- torch.round(input, out=None)  #返回相邻最近的整数，四舍五入

- torch.trunc(input, out=None)  #返回整数部分数值
- torch.frac(tensor, out=None)  #返回小数部分数值

- torch.fmod(input, divisor, out=None)  #返回input/divisor的余数
- torch.remainder(input, divisor, out=None)  #同上

## torch.matmul
- mm只能进行矩阵乘法,也就是输入的两个tensor维度只能是(n×m)(n\times m)(n×m)和(m×p)(m\times p)(m×p)
- bmm是两个三维张量相乘, 两个tensor维度是(b×n×m)和(b×m×p)得到 (b×n×p), 第一维b代表batch_size。
- matmul可以进行张量乘法, 输入可以是高维。

- scores = torch.matmul(x, x.transpose(-2, -1)) / math.sqrt(d_k)

- [torch.transpose](https://pytorch.org/docs/stable/torch.html#torch.transpose) # tonser的转置

In [2]:
x1 = torch.randn(2, 5, 10)
x1

tensor([[[ 0.0608, -0.1447, -0.3057,  0.9118, -0.3778,  1.2587, -1.7109,
          -1.0704,  0.4352, -2.0029],
         [ 0.9735,  1.0512, -1.4398, -0.6600,  0.3955,  0.3646,  0.0474,
          -1.5265,  0.0718,  0.4676],
         [-0.5715, -1.2914,  0.1073, -0.3753,  0.5765, -0.9402, -1.1904,
           0.5456,  0.1140, -0.1685],
         [ 0.4498,  0.7682,  0.2298,  0.6669, -1.0050,  1.4804,  0.5312,
           1.0791, -0.7552, -0.3538],
         [-0.8476, -0.7348, -0.9190,  0.1542,  0.4850, -0.5129,  3.2134,
           1.1763,  0.1987,  1.1999]],

        [[ 1.1443,  0.6204,  0.6688, -0.7729,  0.1621,  0.0467,  0.8106,
           1.8824, -0.2517,  1.4625],
         [ 0.7914,  0.0971,  0.2454,  0.2563,  1.5868, -0.2585, -0.5065,
          -1.3138, -0.2943,  0.3584],
         [ 1.2666,  0.3284,  1.6281,  0.7337, -1.0108,  0.1650, -0.0435,
           0.9840, -0.8043,  0.7147],
         [-1.0370,  0.2351, -1.2820,  0.9013,  1.2597, -1.7748, -2.1565,
           0.6012,  2.0741, -0.4460],

In [6]:
x2 = x1.transpose(-2, -1)
x2

tensor([[[ 0.0608,  0.9735, -0.5715,  0.4498, -0.8476],
         [-0.1447,  1.0512, -1.2914,  0.7682, -0.7348],
         [-0.3057, -1.4398,  0.1073,  0.2298, -0.9190],
         [ 0.9118, -0.6600, -0.3753,  0.6669,  0.1542],
         [-0.3778,  0.3955,  0.5765, -1.0050,  0.4850],
         [ 1.2587,  0.3646, -0.9402,  1.4804, -0.5129],
         [-1.7109,  0.0474, -1.1904,  0.5312,  3.2134],
         [-1.0704, -1.5265,  0.5456,  1.0791,  1.1763],
         [ 0.4352,  0.0718,  0.1140, -0.7552,  0.1987],
         [-2.0029,  0.4676, -0.1685, -0.3538,  1.1999]],

        [[ 1.1443,  0.7914,  1.2666, -1.0370,  1.0765],
         [ 0.6204,  0.0971,  0.3284,  0.2351, -0.1866],
         [ 0.6688,  0.2454,  1.6281, -1.2820, -1.2976],
         [-0.7729,  0.2563,  0.7337,  0.9013, -0.2885],
         [ 0.1621,  1.5868, -1.0108,  1.2597,  0.0313],
         [ 0.0467, -0.2585,  0.1650, -1.7748, -0.0154],
         [ 0.8106, -0.5065, -0.0435, -2.1565,  1.1737],
         [ 1.8824, -1.3138,  0.9840,  0.6012, 

In [8]:
y = torch.matmul(x1, x2) #2, 5,10 * 2, 10, 5
y

tensor([[[10.9509,  0.7026,  0.2158,  1.0130, -9.4263],
         [ 0.7026,  7.4071, -2.8955, -1.2250, -1.4394],
         [ 0.2158, -2.8955,  5.1194, -3.5163, -1.3244],
         [ 1.0130, -1.2250, -3.5163,  6.6340,  0.1013],
         [-9.4263, -1.4394, -1.3244,  0.1013, 15.8137]],

        [[ 9.1703, -1.1083,  5.0835, -4.2642,  0.1277],
         [-1.1083,  5.5442, -0.8025,  1.1083,  1.3530],
         [ 5.0835, -0.8025,  8.0778, -5.5296, -3.1245],
         [-4.2642,  1.1083, -5.5296, 17.8355,  0.5264],
         [ 0.1277,  1.3530, -3.1245,  0.5264, 10.6467]]])

In [9]:
y.size()

torch.Size([2, 5, 5])

In [10]:
y / 2

tensor([[[ 5.4754,  0.3513,  0.1079,  0.5065, -4.7131],
         [ 0.3513,  3.7035, -1.4478, -0.6125, -0.7197],
         [ 0.1079, -1.4478,  2.5597, -1.7581, -0.6622],
         [ 0.5065, -0.6125, -1.7581,  3.3170,  0.0506],
         [-4.7131, -0.7197, -0.6622,  0.0506,  7.9068]],

        [[ 4.5851, -0.5541,  2.5418, -2.1321,  0.0639],
         [-0.5541,  2.7721, -0.4012,  0.5542,  0.6765],
         [ 2.5418, -0.4012,  4.0389, -2.7648, -1.5622],
         [-2.1321,  0.5542, -2.7648,  8.9177,  0.2632],
         [ 0.0639,  0.6765, -1.5622,  0.2632,  5.3234]]])

In [13]:
a = '微信 是否 会 收费 ？ 近日 工信部 和 腾讯 公司 的 不同 回应 让 微信 的 未来 显得 扑朔迷离 。 随着 3G 网络 的 普及 ， 许多 国家 和 地区 都 有 像 “ 微信 ” 这样 能够 实现 即时通讯 、 通话 的 手机 应用 。 “ 微信 ” 在 国外 什么样 ？ 它们 收费 吗 ？ 一张 图带 你 了解 海外 “ 微信 ” 。 ____ ____ '  
b = '“ 微信 ” 在 海外'
c = '[ 话筒 ] “ 微信 ” 在 国外 什么样 ？ 它们 收费 吗 ？ [ 话筒 ] [ 思考 ] [ 吃惊 ] [ 吃惊 ]'

In [21]:
print('-' * 110)
print('{}  \033[01;34m {} \033[0m\n'.format('原   文:', a))
print('{} \033[01;35m {} \033[0m\n'.format('参考摘要:', b))
print('{} \033[01;36m {} \033[0m\n'.format('生成摘要:', c))
print('-' * 110)

--------------------------------------------------------------------------------------------------------------
原   文:   微信 是否 会 收费 ？ 近日 工信部 和 腾讯 公司 的 不同 回应 让 微信 的 未来 显得 扑朔迷离 。 随着 3G 网络 的 普及 ， 许多 国家 和 地区 都 有 像 “ 微信 ” 这样 能够 实现 即时通讯 、 通话 的 手机 应用 。 “ 微信 ” 在 国外 什么样 ？ 它们 收费 吗 ？ 一张 图带 你 了解 海外 “ 微信 ” 。 ____ ____  

参考摘要:  “ 微信 ” 在 海外 

生成摘要:  [ 话筒 ] “ 微信 ” 在 国外 什么样 ？ 它们 收费 吗 ？ [ 话筒 ] [ 思考 ] [ 吃惊 ] [ 吃惊 ] 

--------------------------------------------------------------------------------------------------------------


In [22]:

a = '日前 ， 教育部 公布 2012 年度 普通 高等学校 本科专业 设置 备案 或 审批 结果 。 全国 高校 258 个 专业 未 通过 审批 ， 且 很多 是 当下 热门 专业 ， 如 法学 、 会计 、 工商管理 等 ， 有些 专业 已经 被 列入 教育部 的 预警 专业 。 教育界 人士 分析 ， 人才 市场 的 需求 已 开始 出现 “ 供大于求 ” 现象 。'  
b = '258 个 专业 被 否决 !!____!! !!____!! 部分 热门 专业 遭 “ 预警 ”'
c = '教育部 ： 全国 高校 258 个 专业 未 通过 审批 ， 且 很多 是 当下 热门 专业 ， 如 法学 、 会计 、 工商管理 等 专业 已经 审批 结果'


In [23]:
print('-' * 110)
print('{}  \033[01;34m {} \033[0m\n'.format('原   文:', a))
print('{} \033[01;35m {} \033[0m\n'.format('参考摘要:', b))
print('{} \033[01;36m {} \033[0m\n'.format('生成摘要:', c))
print('-' * 110)

--------------------------------------------------------------------------------------------------------------
原   文:   日前 ， 教育部 公布 2012 年度 普通 高等学校 本科专业 设置 备案 或 审批 结果 。 全国 高校 258 个 专业 未 通过 审批 ， 且 很多 是 当下 热门 专业 ， 如 法学 、 会计 、 工商管理 等 ， 有些 专业 已经 被 列入 教育部 的 预警 专业 。 教育界 人士 分析 ， 人才 市场 的 需求 已 开始 出现 “ 供大于求 ” 现象 。 

参考摘要:  258 个 专业 被 否决 !!____!! !!____!! 部分 热门 专业 遭 “ 预警 ” 

生成摘要:  教育部 ： 全国 高校 258 个 专业 未 通过 审批 ， 且 很多 是 当下 热门 专业 ， 如 法学 、 会计 、 工商管理 等 专业 已经 审批 结果 

--------------------------------------------------------------------------------------------------------------
