In [1]:
import torch

In [7]:
b = torch.tensor([2,3,4])
b.size()
b.unsqueeze(1)

tensor([[2],
        [3],
        [4]])

In [6]:
a = torch.tensor([[0.1,0.1,0.3,0.2,0.3],
                  [0.4,0.4,0.1,0.05,0.05],
                  [0.1,0.1,0.1,0.2,0.5]])
a.size()

torch.Size([3, 5])

In [10]:
c = torch.gather(a, 1, b.unsqueeze(1))
c

tensor([[0.3000],
        [0.0500],
        [0.5000]])

In [11]:
torch.log(c)

tensor([[-1.2040],
        [-2.9957],
        [-0.6931]])

In [12]:
import math

In [13]:
math.log(0.5)

-0.6931471805599453