In [6]:
import torch

In [7]:
b = torch.tensor([2,3,4])
b.size()
b.unsqueeze(1)

tensor([[2],
        [3],
        [4]])

In [6]:
a = torch.tensor([[0.1,0.1,0.3,0.2,0.3],
                  [0.4,0.4,0.1,0.05,0.05],
                  [0.1,0.1,0.1,0.2,0.5]])
a.size()

torch.Size([3, 5])

In [10]:
c = torch.gather(a, 1, b.unsqueeze(1))
c

tensor([[0.3000],
        [0.0500],
        [0.5000]])

In [11]:
torch.log(c)

tensor([[-1.2040],
        [-2.9957],
        [-0.6931]])

In [12]:
import math

In [13]:
math.log(0.5)

-0.6931471805599453

## 如何计算多分类的交叉熵损失？

In [1]:
y_true = ['1', '4', '5'] # 样本的真实标签

y_pred = [
    [0.1, 0.6, 0.3, 0, 0, 0, 0, 0, 0, 0],
    [0, 0.3, 0.2, 0, 0.5, 0, 0, 0, 0, 0],
    [0.6, 0.3, 0, 0, 0, 0.1, 0, 0, 0, 0]
]            
# 样本的预测概率
labels = ['0','1','2','3','4','5','6','7','8','9'] # 所有标签

In [2]:
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelBinarizer
from math import log

In [3]:
# 利用sklearn中的log_loss()函数计算交叉熵
sk_log_loss = log_loss(y_true, y_pred, labels=labels)
print("Loss by sklearn is:%s." %sk_log_loss)

Loss by sklearn is:1.1688526324400008.


In [27]:
# 对样本的真实标签进行标签二值化
lb = LabelBinarizer()
lb.fit(labels)
transformed_labels = lb.transform(y_true)
print(transformed_labels)

N = len(y_true)  # 样本个数
K = len(labels)  # 标签个数

eps = 1e-15      # 预测概率的控制值
Loss = 0         # 损失值初始化

for i in range(N):
    for k in range(K):
        # 控制预测概率在[eps, 1-eps]内，避免求对数时出现问题
        if y_pred[i][k] < eps:
            y_pred[i][k] = eps
        if y_pred[i][k] > 1-eps:
            y_pred[i][k] = 1-eps
        # 多分类问题的交叉熵计算公式
        print(transformed_labels[i][k])
        
        print(y_pred[i][k])
        print("---")
        Loss -= transformed_labels[i][k]*log(y_pred[i][k])

Loss /= N
print("Loss by equation is:%s." % Loss)

[[0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]]
0
0.1
---
1
0.6
---
0
0.3
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
0.3
---
0
0.2
---
0
1e-15
---
1
0.5
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
0.6
---
0
0.3
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
1
0.1
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
0
1e-15
---
Loss by equation is:1.1688526324399937.


In [22]:
d = torch.gather(torch.tensor(y_pred), 1, torch.tensor([int(i) for i in y_true], dtype=torch.long).unsqueeze(1))

In [24]:
-torch.log(d)

tensor([[0.5108],
        [0.6931],
        [2.3026]])

In [29]:
2.3026+0.5108+0.6931

3.5065