In [1]:
import torch

In [3]:
?torch.Tensor.scatter_add_

In [4]:
x = torch.rand(2, 5)

In [5]:
x

tensor([[0.5788, 0.9383, 0.4485, 0.3223, 0.4562],
        [0.1863, 0.9070, 0.9751, 0.5211, 0.4711]])

In [11]:
b = torch.ones(3, 5)

In [12]:
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
b.scatter_add(0, torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]]), x)

tensor([[1.5788, 1.9070, 1.9751, 1.3223, 1.4562],
        [1.0000, 1.9383, 1.0000, 1.5211, 1.0000],
        [1.1863, 1.0000, 1.4485, 1.0000, 1.4711]])

In [15]:
b.scatter_add(0, torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]]), x)

tensor([[1.5788, 1.9070, 1.9751, 1.3223, 1.4562],
        [1.0000, 1.9383, 1.0000, 1.5211, 1.0000],
        [1.1863, 1.0000, 1.4485, 1.0000, 1.4711]])