In [18]:
import torch
import torch.nn as nn
import numpy as np

In [5]:
device = torch.device("cuda")

In [7]:
device

device(type='cuda')

In [44]:
x = np.random.randint(0,25,size=[8]) 
x

array([ 8, 14, 10,  4, 11, 20, 13, 19])

In [59]:
in_tensor = np.append(x, + np.zeros([2]))
in_tensor

array([ 8., 14., 10.,  4., 11., 20., 13., 19.,  0.,  0.])

In [60]:
in_tensor = torch.tensor(in_tensor).long()

In [73]:
in_tensor.shape

torch.Size([10])

In [78]:
x = in_tensor.unsqueeze(0).unsqueeze(0)
x 

tensor([[[ 8, 14, 10,  4, 11, 20, 13, 19,  0,  0]]])

In [79]:
oov_token = torch.full((1,1,10), 3).long()

In [80]:
oov_token

tensor([[[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]])

In [82]:
out_tensor = torch.where(x > 15, oov_token, in_tensor)

In [83]:
out_tensor

tensor([[[ 8, 14, 10,  4, 11,  3, 13,  3,  0,  0]]])

In [89]:
z = torch.ne(x, 0).byte().float()
z

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 0., 0.]]])