In [1]:
import torch

In [21]:
x = torch.tensor([[1,2,3,4],
                 [4,3,2,1]], dtype=torch.float32)
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [22]:
x.argmax(dim=1)

tensor([3, 0])

In [23]:
x.dtype

torch.float32

In [24]:
x.softmax(dim=1)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.6439, 0.2369, 0.0871, 0.0321]])

In [25]:
x.argmax(dim=1)

tensor([3, 0])

In [26]:
#unsqueeze, cat, permute

In [30]:
# squeeze 挤压
x.unsqueeze(dim=0).size()

torch.Size([1, 2, 4])

In [31]:
y = torch.randn(1, 4)
y

tensor([[-0.1562, -1.2787,  0.9936, -1.1843]])

In [32]:
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [38]:
torch.cat((x, y), dim=0)   # 第一个参数是元组

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [-0.1562, -1.2787,  0.9936, -1.1843]])

In [39]:
y = torch.randn(1, 4)
y

tensor([[-0.8324,  1.8248, -0.8726,  0.3803]])

In [40]:
torch.cat((x, y), dim=0)  # 合并，其余维度相同

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [-0.8324,  1.8248, -0.8726,  0.3803]])